config/routes.rb
Rails.application.routes.draw do


 get 'search' => "searches#search"


  get 'search/search'
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :public, path: "" do

    root to: 'homes#top'
    get '/about', to: 'homes#about'
    resources :products, only:[:index, :show]
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :customers, only:[:edit, :update] do
        collection do
            get 'unsubscribe'
            get 'my_page'
        end
    end


    delete 'cart_products/destroy_all'
    resources :cart_products, only:[:index, :update, :destroy, :create]
     get 'orders/complete'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  devise_for :admins, controllers: {
     sessinons: 'admins/sessions',
     passwords: 'admins/passwords',
     registrations: 'admins/registrations'
  }


  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'

    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details


  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

  def total_payment
    sum = 0
    self.order_details.each do |order_detail|
      sum += order_detail.subtotal
    end
    sum
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @products_total_payment = calculate(@order)
    # @products = @order.ordered_products
  end

  def calculate(products_total_payment) # 商品合計を算出するメソッド
    @products_total_payment = 0
    @order_details.each {|order_detail|
    tax_in_price = (order_detail.product.price * 1.1).floor
    sub_total_price = tax_in_price * order_detail.amount
    @products_total_payment += sub_total_price
    }
    return @products_total_payment
  end

  # def order_status_update
  #   order = Order.find(params[:id])
  #   order.update(order_params)
  #   redirect_to admin_order_path(order)
  # end


  def making_status_update
    order_detail = OrderDetail.find(params[:id])
    order_detail.update(order_detail_params)
    redirect_to admin_order_path(order_detail.order_id)
  end

  # def product_status_update
  #   order_detail = OrderDetail.find(params[:id])
  #   order_detail.update(order_detail_params)
  #   redirect_to admin_order_path(order_detail.order_id)
  # end


  def update
    @order = Order.find(params[:id])
    @order.status = params[:order][:status]
    @order.update(order_params)
      if @order.status = "入金確認"
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      end
    redirect_back(fallback_location: admin_orders_path)
  end


#   after_order_update do
#   order = self.order
#   if order.update(order_status: "入金確認") == true #　条件分岐 : 注文ステータスが入金確認になったら
#     order_details.all? {|order_detail| order_detail.making_status == "制作待ち"} # 条件分岐 : 制作ステータスをすべて制作待ちにする
#   end
# end

  private
  def order_params
    params.require(:order).permit(:status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:product_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2 class="index-title">注文履歴詳細</h2>
  </div>

  <div class="row mt-3">
    <div class="col-sm-9">
      <table class="table table-borderless">

        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to admin_customer_path(@order.customer) do %>
              <%= @order.customer.last_name %>
              <%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>

          <tr>
            <td>配送先</td>

            <td><%= @order.address %></td>

          </tr>

          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method %></td>
          </tr>

          <tr>
            <td>注文ステータス</td>
            <td><%= form_for (@order), url: admin_order_path(@order) do |f| %>
                <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
                <% end %>
            </td>
          </tr>
        </tbody>

      </table>
    </div>
  </div>

      	 <div class="row mt-3">
    <div class="col-sm-9">

      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <% @order_details.each do |order_detail| %>
          <tbody>
            <tr>
              <td><%= order_detail.product.name %></td>
              <td><%= (order_detail.product.price * 1.1).floor %>円</td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.product.price * order_detail.amount * 1.1).floor %>円</td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
                  <%= f.select :making_status, [["着手不可", "着手不可"], ["製作待ち","製作待ち"], ["製作中","製作中"], ["製作完了","製作完了"]] %>
                  <%= f.submit "更新", class: "btn btn-primary btn-sm ml-3" %>
                <% end %>
                </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>

    <div class="col-sm-3 d-flex">
      <table class="table table-borderless align-self-end">
        <tbody>
          <tr class="border-bottom border-dark">
            <td>商品合計</td>
            <td><%= @products_total_payment %>円</td>
          </tr>

          <tr class="border-bottom border-dark">
            <td>送料</td>
            <td><%= @order.shipping_cost %>円</td>
          </tr>

          <tr class="border-
          bottom border-dark">
            <td>請求合計金額</td>
            <td><%= @products_total_payment + @order.shipping_cost %>円</td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>