config/routes.rb
Rails.application.routes.draw do


 get 'search' => "searches#search"


  get 'search/search'
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :public, path: "" do

    root to: 'homes#top'
    get '/about', to: 'homes#about'
    resources :products, only:[:index, :show]
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :customers, only:[:edit, :update] do
        collection do
            get 'unsubscribe'
            get 'my_page'
        end
    end


    delete 'cart_products/destroy_all'
    resources :cart_products, only:[:index, :update, :destroy, :create]
     get 'orders/complete'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  devise_for :admins, controllers: {
     sessinons: 'admins/sessions',
     passwords: 'admins/passwords',
     registrations: 'admins/registrations'
  }


  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'

    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer

   validates :postal_code, presence: true
   validates :address, presence: true
   validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product


  def total_price
	  (self.product.price*1.1 * self.amount).to_i
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  

   def active_for_authentication?
       super && (is_deleted == false)
   end


   validates :last_name,  presence: true
   validates :first_name, presence: true
   validates :last_name_kana,  presence: true
   validates :first_name_kana, presence: true
   validates :telephone_number, presence: true
   validates :postal_code,  presence: true
   validates :address, presence: true

   def full_name
    self.last_name + " " + self.first_name
   end

  # 住所自動入力(記述間違えてるかもです)
  # include JpPrefecture
  # jp_prefecture :address

  # def address

  # JpPrefecture::Address.find(code: address).try(:name)

  # end

  # def address=(prefecture_name)
  #   self.address = JpPrefecture::Address.find(name: address).code

  # end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @customer = Customer.where("name LIKE ?", "#{words}")
    else
      @customer = Customer.where("name LIKE ?", "%#{words}%")
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :products
  
  validates :name, presence: true
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @genre = Genre.where("name LIKE ?", "#{words}")
    else
      @genre = Genre.where("name LIKE ?", "%#{words}%")
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details


  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

  def total_payment
    sum = 0
    self.order_details.each do |order_detail|
      sum += order_detail.subtotal
    end
    sum
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :product

  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  def subtotal
	  (self.price * self.amount)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :order_details
  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def addTax
   taxed_money = (self.price*1.1).round
  end

end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
     layout 'admin'
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]
  def index
    @products = Product.all.order(updated_at: :desc).page(params[:page]).per(10)
    @product = Product.new
    @genre = Genre.all
  end

  def new
    @products = Product.all.page(params[:page]).per(10)
    @product = Product.new
    @genre = Genre.new
  end

  def create
    # byebug
    @product = Product.new(product_params)
    # @genre = Genre.new
    if @product.save
      flash[:success] = "商品登録完了しました"
      redirect_to admin_product_path(@product)
    else
      flash.now[:warning] = "入力不備があります"
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
      flash[:success] = "商品情報を更新しました"
    else
      render :edit
    end
  end


  private

  def product_params
    params.require(:product).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?

private

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        new_customer_session_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end
  # helper_method :current_cart

  # def current_cart
  #   if session[:cart_product_id]
  #     @cart_product = CartProduct.find(session[:cart_product_id])
  #   else
  #     @cart_product = CartProduct.create
  #     session[:cart_product_id] = @cart_product.id
  #   end
  # end


  # protected



  # def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
    # devise_parameters_sanitizer.permit(:sign_in, keys: [:name])

  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @value)
  end

  private

  def match(value)
    Product.where(name: value).or(Product.where(genre_id: value))
  end

  def forward(value)
    Product.where("name LIKE ?", "#{value}%")        
  end

  def backward(value)
    Product.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Product.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how
    when 'match'
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <h2 class="edit-title">商品編集</h2>
    <%= form_for @product,url: {action: "update"} do |f| %>
      <div class="row">
        <div class="col-xs-4">
          <%= attachment_image_tag @product, :image, size: "300x300",  fallback: "no_image.jpeg"%><br>
          <label>商品画像</label>
          <%= f.attachment_field :image %>
        </div>
          <div class="col-xs-5 col-xs-offset-2">
            <table class="new-form-table">
              <tbody>
                <tr>
                  <th>商品名</th>
                  <td><%= f.text_field :name, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>商品説明</th>
                  <td><%= f.text_area :introduction, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>ジャンル</th>
                  <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
                </tr>
                 <tr>
                  <th>税抜価格</th>
                  <td>  <%= f.text_field :price, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>販売ステータス</th>
                  <td><%= f.select :is_active, [["販売中","false"], ["売り切れ","true"]], include_blank: "--選択してください--" %></td>
                </tr>
              </tbody>
            </table>
            <%= f.submit :変更を保存, class: "btn btn-info" %>
          </div>
            <% end %>
          </div>
        </div>
      </div>

app/views/admin/products/index.html.erb
<h2 class="index-title">商品一覧</h2>
<div class="button"><%= link_to "+", new_admin_product_path %></div>
<table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品</th>
      <th>商品名</th>
      <th>商品説明</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <% @products.each do |product| %>
  <tbody>
    <tr>
      <td><%= product.id %></td>
      <td><%= attachment_image_tag product, :image, size: "60x60", fallback: "no_image.jpeg"%></td>
      <td><%= link_to product.name, admin_product_path(product) %></td>
      <td><%= product.introduction %></td>
      <td><%= product.price %></td>
      <td><%= product.genre.name %></td>
      <td><% if product.is_active == false %>
      販売中
      <% else %>
      販売停止中
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @products %>

app/views/admin/products/new.html.erb
<div class="row1">
  <h2 class="index-title">商品新規登録</h2><br>
    <%= form_for(@product, url: admin_products_path) do |f| %>
   <div class="col-xs-4">
      <div class="product-image">
        <%= attachment_image_tag @product, :image, fallback: "no_image.jpeg", size:"250x250" %>
      </div><br>
      <%= f.attachment_field :image, placeholder: "商品画像" %>
    </div>
    <br><br><br>
      <div class="col-md-5 col-md-offset-2 col-xs-6 col-xs-offset-2">
        <table class="new-form-table">
          <tbody>
            <tr>
              <th>商品名</th>
              <td><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= f.text_area :introduction, class: "form-control" %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
            </tr>
            <tr>
              <th>税抜価格</th>
              <td><%= f.text_field :price, class: "form-control" %></td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td><%= f.select :is_active, [["販売中", "false"], ["販売不可","true"]], include_blank: "--選択してください--" %></td>
            </tr>
          </tbody>
        </table>
        <div class="text-right">
          <%= f.submit "商品登録", class: "btn btn-info" %>
        </div>
        </div>
        <% end %>
</div>

app/views/admin/products/show.html.erb
<h2 class="index-title">商品詳細</h2>
    <div class="row">
      <div class="col-lg-4">
        <%= attachment_image_tag @product, :image, size: "300x300", fallback: "no_image.jpeg"%><br>
      </div>
       <div class="col-xs-8">
        <table class="table">
          <tbody>
            <tr>
              <td>商品名</td>
              <td><%= @product.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @product.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @product.genre.name %></td>
            </tr>
            <tr>
              <td>税込価格</td>
              <td><%= (@product.price*1.1).floor.to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
              <% if @product.is_active == false %>
              販売中
              <% else %>
              販売停止中
              <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      <%= button_to '編集する',edit_admin_product_path(@product.id), method: :get ,class: "btn btn-warning", style: "margin-left:70%;"%>
    </div>
    </div>