config/routes.rb
Rails.application.routes.draw do


 get 'search' => "searches#search"


  get 'search/search'
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :public, path: "" do

    root to: 'homes#top'
    get '/about', to: 'homes#about'
    resources :products, only:[:index, :show]
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :customers, only:[:edit, :update] do
        collection do
            get 'unsubscribe'
            get 'my_page'
        end
    end


    delete 'cart_products/destroy_all'
    resources :cart_products, only:[:index, :update, :destroy, :create]
     get 'orders/complete'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  devise_for :admins, controllers: {
     sessinons: 'admins/sessions',
     passwords: 'admins/passwords',
     registrations: 'admins/registrations'
  }


  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'

    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer

   validates :postal_code, presence: true
   validates :address, presence: true
   validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product


  def total_price
	  (self.product.price*1.1 * self.amount).to_i
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  

   def active_for_authentication?
       super && (is_deleted == false)
   end


   validates :last_name,  presence: true
   validates :first_name, presence: true
   validates :last_name_kana,  presence: true
   validates :first_name_kana, presence: true
   validates :telephone_number, presence: true
   validates :postal_code,  presence: true
   validates :address, presence: true

   def full_name
    self.last_name + " " + self.first_name
   end

  # 住所自動入力(記述間違えてるかもです)
  # include JpPrefecture
  # jp_prefecture :address

  # def address

  # JpPrefecture::Address.find(code: address).try(:name)

  # end

  # def address=(prefecture_name)
  #   self.address = JpPrefecture::Address.find(name: address).code

  # end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @customer = Customer.where("name LIKE ?", "#{words}")
    else
      @customer = Customer.where("name LIKE ?", "%#{words}%")
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :products
  
  validates :name, presence: true
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @genre = Genre.where("name LIKE ?", "#{words}")
    else
      @genre = Genre.where("name LIKE ?", "%#{words}%")
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details


  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

  def total_payment
    sum = 0
    self.order_details.each do |order_detail|
      sum += order_detail.subtotal
    end
    sum
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :product

  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  def subtotal
	  (self.price * self.amount)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :order_details
  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def addTax
   taxed_money = (self.price*1.1).round
  end

end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
     layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?

private

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        new_customer_session_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end
  # helper_method :current_cart

  # def current_cart
  #   if session[:cart_product_id]
  #     @cart_product = CartProduct.find(session[:cart_product_id])
  #   else
  #     @cart_product = CartProduct.create
  #     session[:cart_product_id] = @cart_product.id
  #   end
  # end


  # protected



  # def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
    # devise_parameters_sanitizer.permit(:sign_in, keys: [:name])

  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @value)
  end

  private

  def match(value)
    Product.where(name: value).or(Product.where(genre_id: value))
  end

  def forward(value)
    Product.where("name LIKE ?", "#{value}%")        
  end

  def backward(value)
    Product.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Product.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how
    when 'match'
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-text">
  made by とんこつ醤油
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="top-container">
    <div class="navbar-header">
      <div class="rogo">
        <a href="/"><%= image_tag "rogo.jpeg" %>
      </div>
    <nav>
      <ul class="nav-list">
      <% if customer_signed_in? %>
          <!--customerがログインしている時 -->

          <div class="menu">
            ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！
            <li class="nav-list-item"><%= link_to "マイページ", my_page_public_customers_path, class: "fas fa-address-card" %></li>
            <li class="nav-list-item"><%= link_to "商品一覧", public_products_path, class: "fas fa-utensils" %></li>
            <li class="nav-list-item"><%= link_to "カート", public_cart_products_path, class: "fas fa-shopping-cart" %></li>
            <li class="nav-list-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
          </div>
          <div class="search">
            <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field 'search[value]', size: "26x4" %>
            <span class="search-button col-xs-12 text-right">
              <%= f.select 'search[how]', options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match" }) %>
              <%= f.submit :"検索" %>
                  <% end %></div>

        <% elsif admin_signed_in? %>
          <!-- 管理者がログインしている時 -->
          <div class="menu">
            <li class="nav-list-item"><%= link_to "商品一覧", admin_products_path, class: "fas fa-utensils" %></li>
            <li class="nav-list-item"><%= link_to "会員一覧", admin_customers_path, class: "fas fa-users" %></li>
            <li class="nav-list-item"><%= link_to "注文履歴一覧", admin_root_path, class: "fas fa-sort-amount-down-alt" %></li>
            <li class="nav-list-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "fas fa-cookie-bite" %></li>
            <li class="nav-list-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
          </div>
          <div class="search">
            <%= form_with url: search_path, method: :get, local: true do |f| %>
              <%= f.text_field 'search[value]', size: "26x4" %>
              <span class="search-button col-xs-12 text-right">
                <%= f.select 'search[how]', options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match" }) %>
                <%= f.submit :"検索" %>
                    <% end %></div>
        <% else %>
          <!-- ログインしていない時 -->
          <div class="menu">
            <li class="nav-list-item"><%= link_to "About", public_about_path, class: "far fa-comment" %></li>
            <li class="nav-list-item"><%= link_to "商品一覧", public_products_path, class: "fas fa-utensils" %></li>
            <li class="nav-list-item"><%= link_to "新規登録", new_customer_registration_path, class: "fas fa-user-plus" %></li>
            <li class="nav-list-item"><%= link_to "ログイン", new_customer_session_path, class: "fas fa-sign-in-alt" %></li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>namespace - admin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<% content_for :content do %>  
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f3294f4f4d.js" crossorigin="anonymous"></script>


  </head>
    <body id="wrapper" style="background-color: white; font-family: 'Alegreya Sans SC', sans-serif; color: #000000;">
      <div class="big-container">
        <!-- ヘッダー -->
        <div class="header">
          <%= render "layouts/header" %>
        </div>
        <!-- Body部分 -->
        <div class="body">
          <div class="container" style="margin-top: 20px;">
            <% flash.each do |message_type, message| %>
              <%= message %>
            <% end %>
            <%= yield %>
          </div>
          <div class="push"></div>
        </div>
        <div class="footer">
          <!-- フッター -->
          <%= render "layouts/footer" %>
        </div>
      </div>
    </body>
</html>